import { Platform } from 'react-native';
import { StrategyData } from './strategy-generator';

// ===== Plain Text Export =====
export function strategyToText(s: StrategyData): string {
  let out = '';
  out += `${'='.repeat(50)}\n`;
  out += `${s.title}\n`;
  out += `${'='.repeat(50)}\n\n`;
  out += `${s.summary}\n\n`;

  out += `--- Ken 最在意 ---\n`;
  out += `${s.kenCoreCaresAbout}\n`;
  out += `原因：${s.kenCoreCaresWhy}\n\n`;

  out += `--- Ken 看這件事的角度 ---\n`;
  s.kenMindset?.forEach((m, i) => {
    out += `${i + 1}. [${m.angle}] ${m.detail}\n`;
  });

  out += `\n--- 公司目標對齊 ---\n`;
  s.companyGoals?.forEach(g => {
    const status = g.status === 'aligned' ? 'ALIGNED' : g.status === 'partial' ? 'PARTIAL' : 'GAP';
    out += `[${status}] ${g.goal} — ${g.note}\n`;
  });

  out += `\n--- Ken 可能會問的問題 ---\n`;
  s.qaCards?.forEach((qa, i) => {
    out += `\nQ${i + 1}: ${qa.question}\n`;
    out += `  背後意圖：${qa.intent}\n`;
    out += `  建議回答：${qa.answer}\n`;
    out += `  ★ 關鍵句：${qa.keyPoint}\n`;
  });

  out += `\n--- 講出來就能推進的金句 ---\n`;
  s.powerPhrases?.forEach(p => {
    const level = p.level === 'critical' ? '★★★' : p.level === 'high' ? '★★' : '★';
    out += `${level} 「${p.phrase}」 → ${p.effect}\n`;
  });

  out += `\n--- 地雷句（講了會被唸）---\n`;
  s.dangerPhrases?.forEach(d => {
    out += `✕ 「${d.phrase}」 → ${d.consequence}\n`;
  });

  out += `\n--- 隱藏風險 ---\n`;
  s.hiddenRisks?.forEach(r => {
    out += `[${r.severity?.toUpperCase()}] ${r.risk}\n`;
    out += `  應對：${r.mitigation}\n`;
  });

  out += `\n--- DO vs DON'T ---\n`;
  s.dosAndDonts?.forEach(dd => {
    out += `✓ DO: ${dd.do}\n`;
    out += `✕ DON'T: ${dd.dont}\n\n`;
  });

  out += `--- Ken 的獨特觀點 ---\n`;
  s.uniquePerspectives?.forEach(p => {
    out += `⚡ ${p.perspective}\n  ${p.explanation}\n\n`;
  });

  out += `--- 可延伸議題 ---\n`;
  s.extendedTopics?.forEach((t, i) => {
    out += `${i + 1}. ${t.topic} — ${t.why}\n`;
  });

  out += `\n--- 完整話術腳本 ---\n`;
  out += `[開場] 「${s.scripts?.opening}」\n\n`;
  s.scripts?.keyTransitions?.forEach((t, i) => {
    out += `[轉折${i + 1}] 「${t}」\n\n`;
  });
  out += `[收尾] 「${s.scripts?.closing}」\n`;

  out += `\n${'='.repeat(50)}\n`;
  out += `Generated by Ken Talk\n`;

  return out;
}

// ===== Download helpers =====
export function downloadText(s: StrategyData) {
  if (Platform.OS !== 'web') return;
  const text = strategyToText(s);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${s.title}_溝通策略.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function downloadWord(s: StrategyData) {
  if (Platform.OS !== 'web') return;

  const docx = await import('docx');
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, TableRow, TableCell, Table, WidthType } = docx;

  const RED = 'C00000';
  const BLUE = '2F5496';
  const GREEN = '548235';
  const ORANGE = 'ED7D31';
  const GRAY = '7F7F7F';

  const hr = () => new Paragraph({
    border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'DDDDDD' } },
    spacing: { after: 200 },
  });

  const sectionHead = (text: string, color = RED) => new Paragraph({
    children: [new TextRun({ text, bold: true, size: 28, color, font: 'Microsoft JhengHei' })],
    spacing: { before: 400, after: 200 },
    heading: HeadingLevel.HEADING_2,
  });

  const children: any[] = [];

  // Title
  children.push(new Paragraph({
    children: [new TextRun({ text: s.title, bold: true, size: 44, color: RED, font: 'Microsoft JhengHei' })],
    spacing: { after: 100 },
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: s.summary, size: 24, color: GRAY, font: 'Microsoft JhengHei' })],
    spacing: { after: 300 },
  }));
  children.push(hr());

  // Ken 最在意
  children.push(sectionHead('Ken 最在意'));
  children.push(new Paragraph({
    children: [new TextRun({ text: s.kenCoreCaresAbout, bold: true, size: 28, font: 'Microsoft JhengHei' })],
    spacing: { after: 80 },
  }));
  children.push(new Paragraph({
    children: [new TextRun({ text: s.kenCoreCaresWhy, size: 22, color: GRAY, font: 'Microsoft JhengHei' })],
    spacing: { after: 200 },
  }));
  children.push(hr());

  // Ken 的角度
  children.push(sectionHead('Ken 看這件事的角度', BLUE));
  s.kenMindset?.forEach((m, i) => {
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `${i + 1}. `, bold: true, size: 22, color: BLUE }),
        new TextRun({ text: m.angle, bold: true, size: 22, font: 'Microsoft JhengHei' }),
      ],
      spacing: { after: 40 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: m.detail, size: 22, color: GRAY, font: 'Microsoft JhengHei' })],
      spacing: { after: 160 },
      indent: { left: 400 },
    }));
  });
  children.push(hr());

  // 公司目標
  children.push(sectionHead('公司目標對齊', GREEN));
  s.companyGoals?.forEach(g => {
    const statusColor = g.status === 'aligned' ? GREEN : g.status === 'partial' ? ORANGE : RED;
    const statusLabel = g.status === 'aligned' ? 'ALIGNED' : g.status === 'partial' ? 'PARTIAL' : 'GAP';
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `[${statusLabel}] `, bold: true, size: 20, color: statusColor }),
        new TextRun({ text: g.goal, bold: true, size: 22, font: 'Microsoft JhengHei' }),
        new TextRun({ text: ` — ${g.note}`, size: 20, color: GRAY, font: 'Microsoft JhengHei' }),
      ],
      spacing: { after: 120 },
    }));
  });
  children.push(hr());

  // QA
  children.push(sectionHead('Ken 可能會問的問題', ORANGE));
  s.qaCards?.forEach((qa, i) => {
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `Q${i + 1}: `, bold: true, size: 24, color: ORANGE }),
        new TextRun({ text: qa.question, bold: true, size: 24, font: 'Microsoft JhengHei' }),
      ],
      spacing: { before: 200, after: 60 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `背後意圖：${qa.intent}`, size: 20, italics: true, color: ORANGE, font: 'Microsoft JhengHei' })],
      spacing: { after: 60 },
      indent: { left: 400 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `建議回答：`, bold: true, size: 20, font: 'Microsoft JhengHei' }), new TextRun({ text: qa.answer, size: 20, font: 'Microsoft JhengHei' })],
      spacing: { after: 60 },
      indent: { left: 400 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `★ 關鍵句：${qa.keyPoint}`, bold: true, size: 22, color: 'D4A017', font: 'Microsoft JhengHei' })],
      spacing: { after: 160 },
      indent: { left: 400 },
    }));
  });
  children.push(hr());

  // Power phrases
  children.push(sectionHead('講出來就能推進的金句', 'D4A017'));
  s.powerPhrases?.forEach(p => {
    const level = p.level === 'critical' ? '★★★ CRITICAL' : p.level === 'high' ? '★★ HIGH' : '★ MEDIUM';
    const color = p.level === 'critical' ? RED : p.level === 'high' ? ORANGE : BLUE;
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `[${level}] `, bold: true, size: 18, color }),
        new TextRun({ text: `「${p.phrase}」`, bold: p.level === 'critical', size: 24, font: 'Microsoft JhengHei' }),
      ],
      spacing: { after: 40 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: p.effect, size: 20, color: GRAY, font: 'Microsoft JhengHei' })],
      spacing: { after: 120 },
      indent: { left: 400 },
    }));
  });
  children.push(hr());

  // Danger phrases
  children.push(sectionHead('地雷句 — 講了會被唸', RED));
  s.dangerPhrases?.forEach(d => {
    children.push(new Paragraph({
      children: [new TextRun({ text: `✕ 「${d.phrase}」`, bold: true, size: 22, color: RED, font: 'Microsoft JhengHei' })],
      spacing: { after: 40 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `→ ${d.consequence}`, size: 20, color: GRAY, font: 'Microsoft JhengHei' })],
      spacing: { after: 120 },
      indent: { left: 400 },
    }));
  });
  children.push(hr());

  // Risks
  children.push(sectionHead('隱藏風險'));
  s.hiddenRisks?.forEach(r => {
    const sevColor = r.severity === 'high' ? RED : r.severity === 'medium' ? ORANGE : GREEN;
    children.push(new Paragraph({
      children: [
        new TextRun({ text: `[${r.severity?.toUpperCase()}] `, bold: true, size: 20, color: sevColor }),
        new TextRun({ text: r.risk, bold: true, size: 22, font: 'Microsoft JhengHei' }),
      ],
      spacing: { after: 40 },
    }));
    children.push(new Paragraph({
      children: [new TextRun({ text: `應對：${r.mitigation}`, size: 20, color: GRAY, font: 'Microsoft JhengHei' })],
      spacing: { after: 120 },
      indent: { left: 400 },
    }));
  });
  children.push(hr());

  // Scripts
  children.push(sectionHead('完整話術腳本', BLUE));
  children.push(new Paragraph({
    children: [new TextRun({ text: '[OPENING]', bold: true, size: 20, color: GREEN }), new TextRun({ text: ` 「${s.scripts?.opening}」`, size: 22, italics: true, font: 'Microsoft JhengHei' })],
    spacing: { after: 160 },
  }));
  s.scripts?.keyTransitions?.forEach((t, i) => {
    children.push(new Paragraph({
      children: [new TextRun({ text: `[TRANSITION ${i + 1}]`, bold: true, size: 20, color: BLUE }), new TextRun({ text: ` 「${t}」`, size: 22, italics: true, font: 'Microsoft JhengHei' })],
      spacing: { after: 160 },
    }));
  });
  children.push(new Paragraph({
    children: [new TextRun({ text: '[CLOSING]', bold: true, size: 20, color: RED }), new TextRun({ text: ` 「${s.scripts?.closing}」`, size: 22, italics: true, font: 'Microsoft JhengHei' })],
    spacing: { after: 200 },
  }));

  // Footer
  children.push(hr());
  children.push(new Paragraph({
    children: [new TextRun({ text: 'Generated by Ken Talk', size: 18, color: 'BFBFBF' })],
    alignment: AlignmentType.CENTER,
  }));

  const doc = new Document({
    sections: [{ children }],
  });

  const buffer = await Packer.toBlob(doc);
  const url = URL.createObjectURL(buffer);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${s.title}_溝通策略.docx`;
  a.click();
  URL.revokeObjectURL(url);
}
